# Build settings
title: Dr Steven Hawes
description: This is a website about me
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]

# Pagination 
paginate: 3
paginate_path: /blog/page:num/

comments: true



sass:
  sass_dir: _sass
  style: compressed # expanded

google_analytics: UA-146477071-1
repository: shawes/shawes.github.io
#disqus_shortname: "nandothemes"
#disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Steve Hawes
  job: Marine and Data Scientist
  thumb: assets/images/author.jpg
  email: maxhawes@gmail.com
  url: https://stevehawes.me/
  github: https://github.com/shawes
  twitter: https://twitter.com/stevehawes
  linkedin: https://linkedin.com/in/steven-hawes-biologist
  codestats: https://codestats.net/users/shawes
  researchgate: https://www.researchgate.net/profile/Steven_Hawes
  orchid: https://orcid.org/0000-0003-4463-3419
  googlescholar: https://scholar.google.com.sg/citations?user=ouQvUUQAAAAJ&hl=en&oi=ao
  figshare: https://figshare.com/authors/Steven_Hawes/708286
  zotero: https://www.zotero.org/shawes

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog
  - slug: cv
    title: CV


exclude: ["config.rb", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile", "personal-website.code-workspace"]